language: python
python:
  - "2.7"
install:
  # Build/test dependencies
  - pip install -r ./django-project-template/requirements/local.txt
  # Get fab to test fab
before_script:
  # Allow us to SSH passwordless to localhost

script:
  # Normal tests
  - python django-project-template/manage.py test
