# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-27 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('category', models.CharField(choices=[('hardware', 'hardware'), ('fruits', 'fruits'), ('couture', 'couture')], default='fruits', max_length=20)),
                ('status', models.IntegerField(choices=[(0, 'open'), (1, 'closed')], default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'shop',
            },
        ),
    ]
